// Code generated by protoc-gen-go. DO NOT EDIT.
// source: definition.proto

package definition

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetItemMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemMessage) Reset()         { *m = GetItemMessage{} }
func (m *GetItemMessage) String() string { return proto.CompactTextString(m) }
func (*GetItemMessage) ProtoMessage()    {}
func (*GetItemMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f461df25659d4bef, []int{0}
}

func (m *GetItemMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemMessage.Unmarshal(m, b)
}
func (m *GetItemMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemMessage.Marshal(b, m, deterministic)
}
func (m *GetItemMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemMessage.Merge(m, src)
}
func (m *GetItemMessage) XXX_Size() int {
	return xxx_messageInfo_GetItemMessage.Size(m)
}
func (m *GetItemMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemMessage proto.InternalMessageInfo

type ItemMessage struct {
	Item                 []byte   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemMessage) Reset()         { *m = ItemMessage{} }
func (m *ItemMessage) String() string { return proto.CompactTextString(m) }
func (*ItemMessage) ProtoMessage()    {}
func (*ItemMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f461df25659d4bef, []int{1}
}

func (m *ItemMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemMessage.Unmarshal(m, b)
}
func (m *ItemMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemMessage.Marshal(b, m, deterministic)
}
func (m *ItemMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemMessage.Merge(m, src)
}
func (m *ItemMessage) XXX_Size() int {
	return xxx_messageInfo_ItemMessage.Size(m)
}
func (m *ItemMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ItemMessage proto.InternalMessageInfo

func (m *ItemMessage) GetItem() []byte {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*GetItemMessage)(nil), "GetItemMessage")
	proto.RegisterType((*ItemMessage)(nil), "ItemMessage")
}

func init() { proto.RegisterFile("definition.proto", fileDescriptor_f461df25659d4bef) }

var fileDescriptor_f461df25659d4bef = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x49, 0x4d, 0xcb,
	0xcc, 0xcb, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x12, 0xe0, 0xe2,
	0x73, 0x4f, 0x2d, 0xf1, 0x2c, 0x49, 0xcd, 0xf5, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0x52,
	0xe4, 0xe2, 0x46, 0xe2, 0x0a, 0x09, 0x71, 0xb1, 0x64, 0x96, 0xa4, 0xe6, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0xf0, 0x04, 0x81, 0xd9, 0x46, 0x6e, 0x5c, 0x22, 0xc1, 0xf9, 0x45, 0x25, 0x99, 0x79, 0xe9,
	0x01, 0x45, 0x99, 0xf9, 0x45, 0x99, 0x25, 0x95, 0x81, 0xa5, 0xa9, 0xa5, 0xa9, 0x42, 0x7a, 0x5c,
	0xdc, 0xee, 0xa9, 0x25, 0x7e, 0xa9, 0x15, 0x60, 0x03, 0x85, 0xf8, 0xf5, 0x50, 0x8d, 0x96, 0xe2,
	0xd1, 0x43, 0xb6, 0x88, 0x21, 0x89, 0x0d, 0xec, 0x06, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x89, 0xc5, 0xbc, 0x0a, 0x97, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SortingPriorityQueueClient is the client API for SortingPriorityQueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SortingPriorityQueueClient interface {
	GetNextItem(ctx context.Context, in *GetItemMessage, opts ...grpc.CallOption) (*ItemMessage, error)
}

type sortingPriorityQueueClient struct {
	cc *grpc.ClientConn
}

func NewSortingPriorityQueueClient(cc *grpc.ClientConn) SortingPriorityQueueClient {
	return &sortingPriorityQueueClient{cc}
}

func (c *sortingPriorityQueueClient) GetNextItem(ctx context.Context, in *GetItemMessage, opts ...grpc.CallOption) (*ItemMessage, error) {
	out := new(ItemMessage)
	err := c.cc.Invoke(ctx, "/SortingPriorityQueue/GetNextItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SortingPriorityQueueServer is the server API for SortingPriorityQueue service.
type SortingPriorityQueueServer interface {
	GetNextItem(context.Context, *GetItemMessage) (*ItemMessage, error)
}

// UnimplementedSortingPriorityQueueServer can be embedded to have forward compatible implementations.
type UnimplementedSortingPriorityQueueServer struct {
}

func (*UnimplementedSortingPriorityQueueServer) GetNextItem(ctx context.Context, req *GetItemMessage) (*ItemMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextItem not implemented")
}

func RegisterSortingPriorityQueueServer(s *grpc.Server, srv SortingPriorityQueueServer) {
	s.RegisterService(&_SortingPriorityQueue_serviceDesc, srv)
}

func _SortingPriorityQueue_GetNextItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortingPriorityQueueServer).GetNextItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SortingPriorityQueue/GetNextItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortingPriorityQueueServer).GetNextItem(ctx, req.(*GetItemMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _SortingPriorityQueue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SortingPriorityQueue",
	HandlerType: (*SortingPriorityQueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNextItem",
			Handler:    _SortingPriorityQueue_GetNextItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "definition.proto",
}
