[package]
name = "sp_error"
version = "0.1.0"
authors = ["Pete Travers <traverspw@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.2.1"
tonic = "0.1.1"

[dependencies.rocksdb]
version = "0.14.0"
default-features = false
features = ["lz4"]
